DROP TABLE IF EXISTS publisher;
CREATE TABLE publisher(
    id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(225) NOT NULL
) ENGINE=InnoDB;

DROP TABLE IF EXISTS book;
CREATE TABLE book(
    id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    publisher_id INT(4) UNSIGNED NOT NULL,
    book_code VARCHAR(100) NOT NULL,
    title VARCHAR(150) NOT NULL,
    summary VARCHAR(225),
    keywords VARCHAR(225),
    FOREIGN KEY(publisher_id) REFERENCES publisher(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS author;
CREATE TABLE author(
    id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS book_detail;
CREATE TABLE book_detail(
    id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    book_id INT(4) UNSIGNED NOT NULL,
    author_id INT(4) UNSIGNED NOT NULL,
    FOREIGN KEY(book_id) REFERENCES book(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(author_id) REFERENCES author(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
